name: Build Games API

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/Games.Api/**'
      - 'src/Application/**'
      - 'src/Domain/**'
      - 'src/Infrastructure/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/Games.Api/**'
      - 'src/Application/**'
      - 'src/Domain/**'
      - 'src/Infrastructure/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/Games.Api/Games.Api.csproj
    
    - name: Build Games API
      run: dotnet build src/Games.Api/Games.Api.csproj --no-restore --configuration Release
    
    # - name: Run Games API Tests
    #   run: dotnet test tests/ --filter "Category=GamesAPI" --configuration Release --verbosity normal