name: Build Application

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/Application/**'
      - 'src/Domain/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/Application/**'
      - 'src/Domain/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/Application/Application.csproj
    
    - name: Build Application
      run: dotnet build src/Application/Application.csproj --no-restore --configuration Release
    
    - name: Run Application Tests
      run: dotnet test tests/Application.Tests --filter "Category=Application" --configuration Release --verbosity normal