name: Build Infrastructure

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/Infrastructure/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/Infrastructure/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/Infrastructure/Infrastructure.csproj
    
    - name: Build Infrastructure
      run: dotnet build src/Infrastructure/Infrastructure.csproj --no-restore --configuration Release
    
    - name: Run Infrastructure Tests
      run: dotnet test tests/Infrastructure.Tests --filter "Category=Infrastructure" --configuration Release --verbosity normal