name: Build Identity CQRS

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/Application/Identity.CQRS/**'
      - 'src/Domain/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/Application/Identity.CQRS/**'
      - 'src/Domain/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/Application/Identity.CQRS/Identity.CQRS.csproj
    
    - name: Build Identity.CQRS
      run: dotnet build src/Application/Identity.CQRS/Identity.CQRS.csproj --no-restore --configuration Release
    
    # - name: Run Identity CQRS Tests
    #   run: dotnet test tests/ --filter "Category=IdentityCQRS" --configuration Release --verbosity normal